Repository dadoonet/fscrawler, pull requests merged in 2018-09, with the labels that each got.

#597 Add LGTM code quality badges
  README.md
Labels: new

#594 Update to Elasticsearch 6.4.1
  .travis.yml
  core/src/main/java/fr/pilato/elasticsearch/crawler/fs/FsParser.java
  docs/source/fscrawler.ini
  elasticsearch-client/src/main/java/fr/pilato/elasticsearch/crawler/fs/client/ElasticsearchClient.java
  elasticsearch-client/src/main/java/fr/pilato/elasticsearch/crawler/fs/client/ElasticsearchClientManager.java
  integration-tests/src/test/java/fr/pilato/elasticsearch/crawler/fs/test/integration/AbstractFsCrawlerITCase.java
  integration-tests/src/test/java/fr/pilato/elasticsearch/crawler/fs/test/integration/AbstractITCase.java
  integration-tests/src/test/java/fr/pilato/elasticsearch/crawler/fs/test/integration/AbstractRestITCase.java
  integration-tests/src/test/java/fr/pilato/elasticsearch/crawler/fs/test/integration/ElasticsearchClientIT.java
  integration-tests/src/test/java/fr/pilato/elasticsearch/crawler/fs/test/integration/FsCrawlerImplAllDocumentsIT.java
  integration-tests/src/test/java/fr/pilato/elasticsearch/crawler/fs/test/integration/FsCrawlerRestIT.java
  integration-tests/src/test/java/fr/pilato/elasticsearch/crawler/fs/test/integration/FsCrawlerTestDefaultsIT.java
  integration-tests/src/test/java/fr/pilato/elasticsearch/crawler/fs/test/integration/FsCrawlerTestFilenameAsIdIT.java
  integration-tests/src/test/java/fr/pilato/elasticsearch/crawler/fs/test/integration/FsCrawlerTestIgnoreFoldersIT.java
  integration-tests/src/test/java/fr/pilato/elasticsearch/crawler/fs/test/integration/FsCrawlerTestIngestPipelineIT.java
  integration-tests/src/test/java/fr/pilato/elasticsearch/crawler/fs/test/integration/FsCrawlerTestJsonSupportIT.java
  integration-tests/src/test/java/fr/pilato/elasticsearch/crawler/fs/test/integration/FsCrawlerTestRawIT.java
  integration-tests/src/test/java/fr/pilato/elasticsearch/crawler/fs/test/integration/FsCrawlerTestRemoveDeletedIT.java
  integration-tests/src/test/java/fr/pilato/elasticsearch/crawler/fs/test/integration/FsCrawlerTestStoreSourceIT.java
  integration-tests/src/test/java/fr/pilato/elasticsearch/crawler/fs/test/integration/FsCrawlerTestSubDirsIT.java
  pom.xml
  rest/src/main/java/fr/pilato/elasticsearch/crawler/fs/rest/ServerStatusApi.java
  travis.sh
Labels: update

#602 Update to Jackson 2.9.7
  pom.xml
Labels: update

#604 Update ossindex-maven-plugin to 3.0.1
  pom.xml
Labels: update

#603 Update to Tika 1.19
  .travis.yml
  docs/source/fscrawler.ini
  pom.xml
  tika/src/main/java/fr/pilato/elasticsearch/crawler/fs/tika/TikaDocParser.java
  tika/src/test/java/fr/pilato/elasticsearch/crawler/fs/tika/TikaDocParserTest.java
  travis.sh
Labels: update

#609 Dump stack when not able to close FSCrawler
  core/src/main/java/fr/pilato/elasticsearch/crawler/fs/FsCrawlerImpl.java
Labels: update

#610 Add a Noop Parser
  core/src/main/java/fr/pilato/elasticsearch/crawler/fs/FsCrawlerImpl.java
  core/src/main/java/fr/pilato/elasticsearch/crawler/fs/FsParser.java
  core/src/main/java/fr/pilato/elasticsearch/crawler/fs/FsParserAbstract.java
  core/src/main/java/fr/pilato/elasticsearch/crawler/fs/FsParserLocal.java
  core/src/main/java/fr/pilato/elasticsearch/crawler/fs/FsParserNoop.java
  core/src/main/java/fr/pilato/elasticsearch/crawler/fs/FsParserSsh.java
Labels: bug

#611 Add Release Drafter to automatically generate the release notes
  .github/release-drafter.yml
Labels: doc
