Repository dadoonet/fscrawler, pull requests merged in 2019-03, with the labels that each got.

#693 Move `fs.pdf_ocr` setting to `fs.ocr.pdf_strategy`
  docs/source/index.rst
  docs/source/user/ocr.rst
  docs/source/user/tips.rst
  settings/src/main/java/fr/pilato/elasticsearch/crawler/fs/settings/Fs.java
  settings/src/main/java/fr/pilato/elasticsearch/crawler/fs/settings/Ocr.java
  test-documents/src/main/resources/documents/test-ocr.docx
  test-documents/src/main/resources/documents/test-ocr.pdf
  tika/src/main/java/fr/pilato/elasticsearch/crawler/fs/tika/TikaInstance.java
  tika/src/test/java/fr/pilato/elasticsearch/crawler/fs/tika/TikaDocParserTest.java
  tika/src/test/resources/log4j2.xml
Labels: update

#694 Display full names when catching parsing errors
  core/src/main/java/fr/pilato/elasticsearch/crawler/fs/FsParserAbstract.java
  rest/src/main/java/fr/pilato/elasticsearch/crawler/fs/rest/UploadApi.java
  tika/src/main/java/fr/pilato/elasticsearch/crawler/fs/tika/TikaDocParser.java
  tika/src/test/java/fr/pilato/elasticsearch/crawler/fs/tika/TikaDocParserTest.java
Labels: update

#695 Exclude the PDFParser from the DefaultParser
  tika/src/main/java/fr/pilato/elasticsearch/crawler/fs/tika/TikaInstance.java
Labels: update

#697 Update to elasticsearch 6.6.2
  docs/source/fscrawler.ini
  pom.xml
Labels: update

#699 Use slf4j 1.8.0-beta4
  pom.xml
Labels: update

#700 Add dependency convergence checks
  framework/pom.xml
  pom.xml
  test-documents/pom.xml
  test-framework/pom.xml
  tika/pom.xml
Labels: update

#698 Add Cross-Origin Resource Sharing (CORS) headers to RestServer
  docs/source/admin/fs/rest.rst
  docs/source/user/rest.rst
  integration-tests/it-common/src/main/java/fr/pilato/elasticsearch/crawler/fs/test/integration/AbstractFsCrawlerITCase.java
  integration-tests/it-common/src/main/java/fr/pilato/elasticsearch/crawler/fs/test/integration/AbstractITCase.java
  integration-tests/it-common/src/main/java/fr/pilato/elasticsearch/crawler/fs/test/integration/AbstractRestITCase.java
  integration-tests/it-common/src/main/java/fr/pilato/elasticsearch/crawler/fs/test/integration/FsCrawlerTestRestOnlyIT.java
  rest/src/main/java/fr/pilato/elasticsearch/crawler/fs/rest/CORSFilter.java
  rest/src/main/java/fr/pilato/elasticsearch/crawler/fs/rest/RestServer.java
  settings/src/main/java/fr/pilato/elasticsearch/crawler/fs/settings/FsCrawlerValidator.java
  settings/src/main/java/fr/pilato/elasticsearch/crawler/fs/settings/FsSettings.java
  settings/src/main/java/fr/pilato/elasticsearch/crawler/fs/settings/Rest.java
  settings/src/main/java/fr/pilato/elasticsearch/crawler/fs/settings/ServerUrl.java
  settings/src/test/java/fr/pilato/elasticsearch/crawler/fs/settings/FsCrawlerValidatorTest.java
  settings/src/test/java/fr/pilato/elasticsearch/crawler/fs/settings/FsSettingsParserTest.java
Labels: new

#701 Change log level and display logs only if filters on content
  framework/src/main/java/fr/pilato/elasticsearch/crawler/fs/framework/FsCrawlerUtil.java
Labels: bug

#703 Update to Elasticsearch 6.7.0
  docs/source/fscrawler.ini
  pom.xml
Labels: update

#704 Disable raw metadata by default
  docs/source/admin/fs/local-fs.rst
  integration-tests/it-common/src/main/java/fr/pilato/elasticsearch/crawler/fs/test/integration/FsCrawlerRestIT.java
  integration-tests/it-common/src/main/java/fr/pilato/elasticsearch/crawler/fs/test/integration/FsCrawlerTestRawIT.java
  settings/src/main/java/fr/pilato/elasticsearch/crawler/fs/settings/Fs.java
  settings/src/test/java/fr/pilato/elasticsearch/crawler/fs/settings/FsSettingsParserTest.java
  tika/src/test/java/fr/pilato/elasticsearch/crawler/fs/tika/TikaDocParserTest.java
Labels: breaking, update

#705 Update Elasticsearch to 7.0.0-rc1
  docs/source/fscrawler.ini
  pom.xml
Labels: update

#706 Update Elasticsearch to 5.6.15
  docs/source/fscrawler.ini
  pom.xml
Labels: update
