Repository dadoonet/fscrawler, pull requests merged in 2019-11, with the labels that each got.

#847 sun.jnu.encoding=UTF-8 added in .bat and .sh both
  distribution/src/main/scripts/fscrawler
  distribution/src/main/scripts/fscrawler.bat
Labels: bug

#855 Fix CVE reports until Tika 1.23
  docs/source/fscrawler.ini
  pom.xml
Labels: update

#861 Remove support for Elasticsearch v5
  README.md
  cli/src/main/java/fr/pilato/elasticsearch/crawler/fs/cli/FsCrawlerCli.java
  core/src/main/java/fr/pilato/elasticsearch/crawler/fs/FsCrawlerImpl.java
  distribution/es5/pom.xml
  distribution/es5/src/main/java/fr/pilato/elasticsearch/crawler/fs/cli/FsCrawler.java
  distribution/pom.xml
  docs/source/conf.py
  docs/source/dev/build.rst
  docs/source/fscrawler.ini
  docs/source/index.rst
  docs/source/installation.rst
  docs/src/main/resources/fscrawler.ini
  elasticsearch-client/elasticsearch-client-base/src/main/java/fr/pilato/elasticsearch/crawler/fs/client/ElasticsearchClient.java
  elasticsearch-client/elasticsearch-client-base/src/test/java/fr/pilato/elasticsearch/crawler/fs/client/ElasticsearchClientDummyBase.java
  elasticsearch-client/elasticsearch-client-v5/pom.xml
  elasticsearch-client/elasticsearch-client-v5/src/main/java/fr/pilato/elasticsearch/crawler/fs/client/v5/ElasticsearchClientV5.java
  elasticsearch-client/elasticsearch-client-v5/src/test/java/fr/pilato/elasticsearch/crawler/fs/client/v5/ElasticsearchClientV5Test.java
  elasticsearch-client/elasticsearch-client-v5/src/test/resources/log4j2.xml
  elasticsearch-client/pom.xml
  framework/src/main/java/fr/pilato/elasticsearch/crawler/fs/framework/FsCrawlerUtil.java
  integration-tests/it-common/pom.xml
  integration-tests/it-common/src/main/java/fr/pilato/elasticsearch/crawler/fs/test/integration/FsCrawlerTestUpgradeVersionIT.java
  integration-tests/it-v5/pom.xml
  integration-tests/pom.xml
  pom.xml
  settings/src/main/resources/fr/pilato/elasticsearch/crawler/fs/_default/2/_settings.json
  settings/src/main/resources/fr/pilato/elasticsearch/crawler/fs/_default/2/_settings_folder.json
  settings/src/main/resources/fr/pilato/elasticsearch/crawler/fs/_default/5/_settings.json
  settings/src/main/resources/fr/pilato/elasticsearch/crawler/fs/_default/5/_settings_folder.json
  settings/src/test/java/fr/pilato/elasticsearch/crawler/fs/settings/FsCopyResourcesTest.java
  settings/src/test/java/fr/pilato/elasticsearch/crawler/fs/settings/FsMappingTest.java
  settings/src/test/resources/jobtest/2/_settings.json
  settings/src/test/resources/jobtest/2/_settings_folder.json
  settings/src/test/resources/jobtest/5/_settings.json
  settings/src/test/resources/jobtest/5/_settings_folder.json
  test-framework/src/main/java/fr/pilato/elasticsearch/crawler/fs/test/framework/FsCrawlerUtilForTests.java
Labels: breaking, remove
