Repository dadoonet/fscrawler, pull requests merged in 2019-01, with the labels that each got.

#657 Update Jackson to 2.9.8
  pom.xml
Labels: update

#658 Exit as soon as we close FSCrawler
  core/src/main/java/fr/pilato/elasticsearch/crawler/fs/FsParserAbstract.java
Labels: bug

#663 Add Patterns table to includes and excludes
  docs/source/admin/fs/local-fs.rst
Labels: doc

#666 Don't start docker container in fscrawler-it module
  integration-tests/it-common/pom.xml
  integration-tests/it-v5/pom.xml
  integration-tests/it-v6/pom.xml
  integration-tests/pom.xml
Labels: test

#665 Remove Elasticsearch.Node and Rest deprecated settings
  elasticsearch-client/elasticsearch-client-base/src/main/java/fr/pilato/elasticsearch/crawler/fs/client/ElasticsearchClientUtil.java
  elasticsearch-client/elasticsearch-client-base/src/test/java/fr/pilato/elasticsearch/crawler/fs/client/ElasticsearchClientTest.java
  elasticsearch-client/elasticsearch-client-v5/src/main/java/fr/pilato/elasticsearch/crawler/fs/client/v5/ElasticsearchClientV5.java
  elasticsearch-client/elasticsearch-client-v6/src/main/java/fr/pilato/elasticsearch/crawler/fs/client/v6/ElasticsearchClientV6.java
  integration-tests/it-common/src/main/java/fr/pilato/elasticsearch/crawler/fs/test/integration/AbstractFsCrawlerITCase.java
  integration-tests/it-common/src/main/java/fr/pilato/elasticsearch/crawler/fs/test/integration/AbstractITCase.java
  integration-tests/it-common/src/main/java/fr/pilato/elasticsearch/crawler/fs/test/integration/AbstractRestITCase.java
  integration-tests/it-common/src/main/java/fr/pilato/elasticsearch/crawler/fs/test/integration/FsCrawlerTestRestOnlyIT.java
  rest/src/main/java/fr/pilato/elasticsearch/crawler/fs/rest/RestServer.java
  rest/src/main/java/fr/pilato/elasticsearch/crawler/fs/rest/UploadApi.java
  settings/src/main/java/fr/pilato/elasticsearch/crawler/fs/settings/Elasticsearch.java
  settings/src/main/java/fr/pilato/elasticsearch/crawler/fs/settings/FsCrawlerValidator.java
  settings/src/main/java/fr/pilato/elasticsearch/crawler/fs/settings/FsSettings.java
  settings/src/main/java/fr/pilato/elasticsearch/crawler/fs/settings/Rest.java
  settings/src/main/java/fr/pilato/elasticsearch/crawler/fs/settings/ServerUrl.java
  settings/src/test/java/fr/pilato/elasticsearch/crawler/fs/settings/FsCrawlerValidatorTest.java
  settings/src/test/java/fr/pilato/elasticsearch/crawler/fs/settings/FsSettingsParserTest.java
  settings/src/test/java/fr/pilato/elasticsearch/crawler/fs/settings/FsSettingsTest.java
Labels: breaking, remove

#668 Fix Maven Central and Sonatype links
  docs/source/conf.py
  docs/source/installation.rst
Labels: doc

#669 Add support for Elasticsearch 7.0
  README.md
  core/src/main/java/fr/pilato/elasticsearch/crawler/fs/FsParserAbstract.java
  distribution/es7/pom.xml
  distribution/es7/src/main/java/fr/pilato/elasticsearch/crawler/fs/cli/FsCrawler.java
  distribution/pom.xml
  docs/source/admin/fs/elasticsearch.rst
  docs/source/admin/fs/index.rst
  docs/source/conf.py
  docs/source/dev/build.rst
  docs/source/installation.rst
  elasticsearch-client/elasticsearch-client-base/src/main/java/fr/pilato/elasticsearch/crawler/fs/client/ElasticsearchClient.java
  elasticsearch-client/elasticsearch-client-base/src/main/java/fr/pilato/elasticsearch/crawler/fs/client/ElasticsearchClientUtil.java
  elasticsearch-client/elasticsearch-client-base/src/test/java/fr/pilato/elasticsearch/crawler/fs/client/ElasticsearchClientDummyBase.java
  elasticsearch-client/elasticsearch-client-v5/src/main/java/fr/pilato/elasticsearch/crawler/fs/client/v5/ElasticsearchClientV5.java
  elasticsearch-client/elasticsearch-client-v6/src/main/java/fr/pilato/elasticsearch/crawler/fs/client/v6/ElasticsearchClientV6.java
  elasticsearch-client/elasticsearch-client-v7/pom.xml
  elasticsearch-client/elasticsearch-client-v7/src/main/java/fr/pilato/elasticsearch/crawler/fs/client/v7/ElasticsearchClientV7.java
  elasticsearch-client/elasticsearch-client-v7/src/test/java/fr/pilato/elasticsearch/crawler/fs/client/v7/ElasticsearchClientV7Test.java
  elasticsearch-client/elasticsearch-client-v7/src/test/resources/log4j2.xml
  elasticsearch-client/pom.xml
  framework/src/main/java/fr/pilato/elasticsearch/crawler/fs/framework/FsCrawlerUtil.java
  integration-tests/it-common/pom.xml
  integration-tests/it-common/src/main/java/fr/pilato/elasticsearch/crawler/fs/test/integration/AbstractITCase.java
  integration-tests/it-common/src/main/java/fr/pilato/elasticsearch/crawler/fs/test/integration/ElasticsearchClientIT.java
  integration-tests/it-common/src/main/java/fr/pilato/elasticsearch/crawler/fs/test/integration/FsCrawlerTestFilenameAsIdIT.java
  integration-tests/it-common/src/main/java/fr/pilato/elasticsearch/crawler/fs/test/integration/FsCrawlerTestRawIT.java
  integration-tests/it-common/src/main/java/fr/pilato/elasticsearch/crawler/fs/test/integration/FsCrawlerTestRemoveDeletedIT.java
  integration-tests/it-common/src/main/java/fr/pilato/elasticsearch/crawler/fs/test/integration/FsCrawlerTestUpgradeVersionIT.java
  integration-tests/it-v7/pom.xml
  integration-tests/pom.xml
  pom.xml
  rest/src/main/java/fr/pilato/elasticsearch/crawler/fs/rest/UploadApi.java
  settings/src/main/resources/fr/pilato/elasticsearch/crawler/fs/_default/7/_settings.json
  settings/src/main/resources/fr/pilato/elasticsearch/crawler/fs/_default/7/_settings_folder.json
  settings/src/test/java/fr/pilato/elasticsearch/crawler/fs/settings/FsCopyResourcesTest.java
  settings/src/test/java/fr/pilato/elasticsearch/crawler/fs/settings/FsMappingTest.java
  settings/src/test/resources/jobtest/7/_settings.json
  settings/src/test/resources/jobtest/7/_settings_folder.json
  test-framework/src/main/java/fr/pilato/elasticsearch/crawler/fs/test/framework/FsCrawlerUtilForTests.java
Labels: new

#670 Update to elasticsearch 6.6.0
  docs/source/conf.py
  docs/source/fscrawler.ini
  docs/source/index.rst
  framework/src/main/resources/fscrawler.ini
  pom.xml
Labels: update

#671 Update to elasticsearch 5.6.14
  docs/source/fscrawler.ini
  pom.xml
Labels: update
