Repository dadoonet/fscrawler, pull requests merged in 2020-12, with the labels that each got.

#1046 Fix flaky tests
  test-framework/src/main/java/fr/pilato/elasticsearch/crawler/fs/test/framework/AbstractFSCrawlerTestCase.java
  test-framework/src/test/java/fr/pilato/elasticsearch/crawler/fs/test/framework/AbstractFSCrawlerTestCaseTest.java
Labels: test

#1040 Update to Java 14
  .travis.yml
  beans/src/main/java/fr/pilato/elasticsearch/crawler/fs/beans/Doc.java
  beans/src/main/java/fr/pilato/elasticsearch/crawler/fs/beans/DocParser.java
  beans/src/main/java/fr/pilato/elasticsearch/crawler/fs/beans/FsJob.java
  beans/src/main/java/fr/pilato/elasticsearch/crawler/fs/beans/ScanStatistic.java
  cli/src/main/java/fr/pilato/elasticsearch/crawler/fs/cli/BootstrapChecks.java
  cli/src/main/java/fr/pilato/elasticsearch/crawler/fs/cli/FsCrawlerCli.java
  cli/src/test/java/fr/pilato/elasticsearch/crawler/fs/cli/FsCrawlerCliTest.java
  core/src/main/java/fr/pilato/elasticsearch/crawler/fs/FsParserAbstract.java
  core/src/main/java/fr/pilato/elasticsearch/crawler/fs/FsParserLocal.java
  core/src/main/java/fr/pilato/elasticsearch/crawler/fs/FsParserSsh.java
  crawler/crawler-abstract/src/main/java/fr/pilato/elasticsearch/crawler/fs/crawler/FileAbstractModel.java
  docs/source/installation.rst
  elasticsearch-client/elasticsearch-client-base/src/main/java/fr/pilato/elasticsearch/crawler/fs/client/ESDocumentField.java
  elasticsearch-client/elasticsearch-client-base/src/main/java/fr/pilato/elasticsearch/crawler/fs/client/ElasticsearchClientUtil.java
  elasticsearch-client/elasticsearch-client-base/src/test/java/fr/pilato/elasticsearch/crawler/fs/client/ElasticsearchClientDummyBase.java
  elasticsearch-client/elasticsearch-client-base/src/test/java/fr/pilato/elasticsearch/crawler/fs/client/ElasticsearchClientTest.java
  elasticsearch-client/elasticsearch-client-base/src/test/resources/fr/pilato/elasticsearch/crawler/fs/client/fscrawler-client.properties
  elasticsearch-client/elasticsearch-client-base/src/test/resources/fr/pilato/elasticsearch/crawler/fs/client/v0/fscrawler-client-wrong-version.properties
  elasticsearch-client/elasticsearch-client-v6/src/main/java/fr/pilato/elasticsearch/crawler/fs/client/v6/ElasticsearchClientV6.java
  elasticsearch-client/elasticsearch-client-v7/src/main/java/fr/pilato/elasticsearch/crawler/fs/client/v7/ElasticsearchClientV7.java
  framework/src/main/java/fr/pilato/elasticsearch/crawler/fs/framework/FsCrawlerUtil.java
  framework/src/main/java/fr/pilato/elasticsearch/crawler/fs/framework/JsonUtil.java
  framework/src/main/java/fr/pilato/elasticsearch/crawler/fs/framework/MetaFileHandler.java
  framework/src/main/java/fr/pilato/elasticsearch/crawler/fs/framework/OsValidator.java
  framework/src/main/java/fr/pilato/elasticsearch/crawler/fs/framework/SignTool.java
  framework/src/main/java/fr/pilato/elasticsearch/crawler/fs/framework/StreamsUtil.java
  framework/src/test/java/fr/pilato/elasticsearch/crawler/fs/framework/ByteSizeValueTest.java
  framework/src/test/java/fr/pilato/elasticsearch/crawler/fs/framework/StreamsUtilTest.java
  integration-tests/it-common/src/main/java/fr/pilato/elasticsearch/crawler/fs/test/integration/AbstractITCase.java
  integration-tests/it-common/src/main/java/fr/pilato/elasticsearch/crawler/fs/test/integration/FsCrawlerImplAllDocumentsIT.java
  integration-tests/it-common/src/main/java/fr/pilato/elasticsearch/crawler/fs/test/integration/FsCrawlerRestIT.java
  integration-tests/it-common/src/main/java/fr/pilato/elasticsearch/crawler/fs/test/integration/FsCrawlerTestFilesizeIT.java
  integration-tests/it-common/src/main/java/fr/pilato/elasticsearch/crawler/fs/test/integration/FsCrawlerTestRemoveDeletedIT.java
  integration-tests/it-common/src/main/java/fr/pilato/elasticsearch/crawler/fs/test/integration/FsCrawlerTestRestOnlyIT.java
  integration-tests/it-common/src/main/java/fr/pilato/elasticsearch/crawler/fs/test/integration/FsCrawlerTestSubDirsIT.java
  lgtm.yml
  pom.xml
  rest/pom.xml
  rest/src/main/java/fr/pilato/elasticsearch/crawler/fs/rest/CORSFilter.java
  rest/src/main/java/fr/pilato/elasticsearch/crawler/fs/rest/ServerStatusApi.java
  rest/src/main/java/fr/pilato/elasticsearch/crawler/fs/rest/TimeBasedUUIDGenerator.java
  settings/src/main/java/fr/pilato/elasticsearch/crawler/fs/settings/Elasticsearch.java
  settings/src/main/java/fr/pilato/elasticsearch/crawler/fs/settings/Server.java
  settings/src/test/java/fr/pilato/elasticsearch/crawler/fs/settings/FsCopyResourcesTest.java
  settings/src/test/java/fr/pilato/elasticsearch/crawler/fs/settings/FsCrawlerValidatorTest.java
  settings/src/test/java/fr/pilato/elasticsearch/crawler/fs/settings/FsMappingTest.java
  test-framework/src/main/java/fr/pilato/elasticsearch/crawler/fs/test/framework/AbstractFSCrawlerTestCase.java
  test-framework/src/main/java/fr/pilato/elasticsearch/crawler/fs/test/framework/FSCrawlerReproduceInfoPrinter.java
  test-framework/src/test/java/fr/pilato/elasticsearch/crawler/fs/test/framework/AbstractFSCrawlerTestCaseTest.java
  tika/src/main/java/fr/pilato/elasticsearch/crawler/fs/tika/TikaDocParser.java
  tika/src/main/java/fr/pilato/elasticsearch/crawler/fs/tika/TikaInstance.java
  tika/src/main/java/fr/pilato/elasticsearch/crawler/fs/tika/XmlDocParser.java
Labels: breaking, update

#1049 Update Dockerfile to use JDK14
  contrib/docker-compose-example/Dockerfile-fscrawler
Labels: update

#1050 Fix some sonar reports
  cli/src/main/java/fr/pilato/elasticsearch/crawler/fs/cli/FsCrawlerCli.java
  core/src/main/java/fr/pilato/elasticsearch/crawler/fs/FsCrawlerImpl.java
  framework/src/main/java/fr/pilato/elasticsearch/crawler/fs/framework/Version.java
  integration-tests/it-common/src/main/java/fr/pilato/elasticsearch/crawler/fs/test/integration/FsCrawlerTestIngestPipelineIT.java
  integration-tests/it-common/src/main/resources-binary/samples/test_ingest_pipeline_392/issue-392.pdf
  test-framework/src/main/java/fr/pilato/elasticsearch/crawler/fs/test/framework/AbstractFSCrawlerTestCase.java
Labels: update

#1005 Fix ENTRYPOINT in Dockerfile to allow variable substitution
  contrib/docker-compose-example/Dockerfile-fscrawler
Labels: bug

#929 Update ImageIO to 3.0.3
  core/pom.xml
  integration-tests/it-common/pom.xml
  pom.xml
  tika/pom.xml
Labels: update

#986 Docker-compose REST service instructions
  docs/source/user/tips.rst
Labels: doc
