Repository dadoonet/fscrawler, pull requests merged in 2021-01, with the labels that each got.

#1066 Start fscrawler instead of internal services
  cli/src/main/java/fr/pilato/elasticsearch/crawler/fs/cli/FsCrawlerCli.java
Labels: bug

#1067 Tesseract binary path should not contain the executable filename
  core/src/main/java/fr/pilato/elasticsearch/crawler/fs/FsParserAbstract.java
  docs/source/user/ocr.rst
  framework/src/main/java/fr/pilato/elasticsearch/crawler/fs/framework/MetaFileHandler.java
Labels: doc

#1068 Update Guava to 30.1
  tika/pom.xml
Labels: update

#1085 fscrawler.bat added a CD to move to the appropriate directory
  distribution/src/main/scripts/fscrawler.bat
Labels: bug
