Repository dadoonet/fscrawler, pull requests merged in 2022-01, with the labels that each got.

#1348 Switch to the new sonatype service
  docs/source/conf.py
  docs/source/dev/release.rst
  pom.xml
  release.sh
Labels: update

#1345 Improve documentation for settings
  docs/source/admin/fs/index.rst
  docs/source/admin/fs/local-fs.rst
Labels: doc

#1298 Add more default displayed fields
  settings/src/main/resources/fr/pilato/elasticsearch/crawler/fs/_default/7/_wpsearch_settings.json
  settings/src/test/java/fr/pilato/elasticsearch/crawler/fs/settings/FsMappingTest.java
Labels: new

#1358 `fs.ocr.enabled` is always false
  tika/src/main/java/fr/pilato/elasticsearch/crawler/fs/tika/TikaInstance.java
Labels: bug
