Repository dadoonet/fscrawler, pull requests merged in 2022-12, with the labels that each got.

#1552 Use `file` instead of `File` for facets
  elasticsearch-client/src/main/java/fr/pilato/elasticsearch/crawler/fs/client/WorkplaceSearchClientUtil.java
Labels: bug

#1558 Exclude CVE-2022-1471 vulnerability
  pom.xml
Labels: security

#1562 Windows FSCrawler configuration folder path update
  docs/source/user/tutorial.rst
Labels: doc

#1574 Exclude sonatype-2022-6438 vulnerability
  pom.xml
Labels: security
