Repository dadoonet/fscrawler, pull requests merged in 2023-10, with the labels that each got.

#1729 Docker multi-arch image
  distribution/pom.xml
Labels: new

#1723 Update Elasticsearch 7.x to 7.17.14
  contrib/docker-compose-it-v7/.env
  docs/source/fscrawler.ini
  pom.xml
Labels: dependencies

#1738 Don't hide console logs when running with Docker
  cli/src/main/java/fr/pilato/elasticsearch/crawler/fs/cli/FsCrawlerCli.java
  cli/src/main/resources/log4j2-file.xml
  cli/src/test/java/fr/pilato/elasticsearch/crawler/fs/cli/FsCrawlerCliCommandParserTest.java
  cli/src/test/java/fr/pilato/elasticsearch/crawler/fs/cli/FsCrawlerCliDefaultSettingsTest.java
  cli/src/test/java/fr/pilato/elasticsearch/crawler/fs/cli/FsCrawlerCliLoggerTest.java
  contrib/docker-compose-example-fscrawler/.env
  contrib/docker-compose-example-fscrawler/config/idx/_settings.yaml
  contrib/docker-compose-example-fscrawler/docker-compose.yml
  contrib/src/main/resources/docker-compose-example-fscrawler/.env
Labels: update, component:cli
